- name: Setup Fedora Developer Workstation
  hosts: all
  pre_tasks:
    # Update homebrew and upgrade all packages
    - homebrew:
        update_homebrew: true
        upgrade_all: true
  tasks:
    
