- name: Create a directory if it does not exist
  file:
    path: "/Users/erickrenz/code"
    state: directory
    owner: ekrenz
  tags:
    - always

- name: personal website
  git:
    repo: "https://github.com/erickrenz/ekrenz.com.git" 
    dest: "/Users/erickrenz/code/ekrenz.com/"
  tags:
    - home

